#!/usr/bin/env python3

# SPDX-FileCopyrightText: GARDENA GmbH
#
# SPDX-License-Identifier: LGPL-2.0-or-later

# TODO print traffic class of received messages

import inspect
import os
import sys
import time
from datetime import datetime

from IPython.lib.pretty import pretty

# In order to make this example usable out of the box, extend Python's module
# search path, such that the lemonbeat module will be found in the parent
# directory.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))))

from lemonbeat import *
from lemonbeat import config_file


def pretty_print(address, data):
    device = devices.get(address[0], address[0])
    print(datetime.now(), device, pretty(data))


try:
    devices = {v.address: k for k, v in config_file.load()[1].items()}
except config_file.NoConfigFoundError:
    devices = {}

gw = Gateway(inclusion_message=None)
devices[gw.address] = "DONGLE"
gw.start_service_listener(Service.DEVICE_DESCRIPTION, handler=pretty_print)

while True:
    time.sleep(1)
