#!/usr/bin/env python3

# SPDX-FileCopyrightText: GARDENA GmbH
#
# SPDX-License-Identifier: LGPL-2.0-or-later

# TODO print traffic class of received messages

import inspect
import os
import queue
import sys
import threading
import time
import traceback
from datetime import datetime

from IPython.lib.pretty import pretty

# In order to make this example usable out of the box, extend Python's module
# search path, such that the lemonbeat module will be found in the parent
# directory.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))))

from lemonbeat import *
from lemonbeat import config_file
from lemonbeat.mower_helpers import is_mower, decode_value_report, decode_status_report


def conditional_pretty_print(address, data):
    device = devices.get(address[0])
    if device is not None:
        print(datetime.now(), device[0], pretty(data))


def status_handler(address, data):
    conditionally_get_device_info_and_continue(print_status_report, address, datetime.now(), data)


def print_status_report(device, device_info, timestamp, data):
    if is_mower(device_info[0]):
        data = decode_status_report(data, device_info[1])
    print(timestamp, device[0], pretty(data))


def value_handler(address, data):
    conditionally_get_device_info_and_continue(print_value_report, address, datetime.now(), data)


def print_value_report(device, device_info, timestamp, data):
    if is_mower(device_info[0]):
        data = decode_value_report(data, device_info[1])
    print(timestamp, device[0], pretty(data))


def conditionally_get_device_info_and_continue(continue_fn, address, timestamp, data):
    device = devices.get(address[0])
    if device is None:
        return

    start_request = False
    with lock:
        device_info = device_infos.get(address[0])
        if device_info is None:
            report_queue = report_queues.get(address[0])
            if report_queue is None:
                start_request = True
                report_queue = queue.Queue()
                report_queues[address[0]] = report_queue

    if device_info is not None:
        continue_fn(device, device_info, timestamp, data)
        return

    report_queue.put((continue_fn, device, timestamp, data))

    if start_request:
        thread = threading.Thread(target=get_device_info, args=(device,))
        thread.daemon = True
        thread.start()


def get_device_info(device):
    # noinspection PyBroadException
    try:
        print(f"Requesting device description from {device[0]}.")
        device_description = device[1].get_device_description()
        print(f"Requesting value description from {device[0]}.")
        value_description = device[1].get_value_description()
    except Exception as e:  # pylint: disable=broad-except
        if isinstance(e, RequestTimeoutError):
            print(f"Timeout while requesting device info from {device[0]}.")
        else:
            print(f"Error while requesting device info from {device[0]}.")
            traceback.print_exc()
        with lock:
            del report_queues[device[1].address]
    else:
        device_info = device_description, value_description
        with lock:
            device_infos[device[1].address] = device_info
            report_queue = report_queues.pop(device[1].address)
        while True:
            try:
                continue_fn, device, timestamp, data = report_queue.get(block=False)
            except queue.Empty:
                break
            continue_fn(device, device_info, timestamp, data)


devices = {v.address: (k, v) for k, v in config_file.load()[1].items()}
device_infos = {}
report_queues = {}
lock = threading.Lock()

gw = Gateway(inclusion_message=None)
devices[gw.address] = ("DONGLE", gw)
gw.start_service_listener(Service.STATUS, handler=status_handler)
gw.start_service_listener(Service.VALUE, handler=value_handler)
gw.start_service_listener(Service.DEVICE_DESCRIPTION, handler=conditional_pretty_print)

while True:
    time.sleep(1)
